allprojects {
    repositories {
        maven {
            name = "Pjiesco-Releases"
            url = uri("https://repo.pjiesco.com/releases")
        }
        // TODO: remove this, in favor of proper repository
        mavenLocal() // Use Maven local for TP SDK because snapshot repo is not available.
        mavenCentral()
    }
}

ext.tppSDKVersion = '9.0.0+'
