plugins {
    id 'java'
    id 'com.github.gmazzo.buildconfig' version '3.0.0'
    id 'com.christophecvb.touchportal.plugin-packager' version '7.0.0-alpha-3'
}

repositories {
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

def versionMajor = 3
def versionMinor = 0
def versionPatch = 0

def mainClassSimpleName = 'TouchPortalSpotifyPlugin'
def mainClassPackage = 'com.github.ChristopheCVB.TouchPortal.Spotify'
group mainClassPackage
version "${versionMajor}.${versionMinor}.${versionPatch}"

tpPlugin.mainClassSimpleName = mainClassSimpleName

buildConfig {
    packageName = project.group

    buildConfigField 'String', 'NAME', "\"${project.name}\""
    buildConfigField 'String', 'VERSION_NAME', "\"${version}\""
    buildConfigField 'long', 'VERSION_CODE', (versionMajor * 1000 + versionMinor * 100 + versionPatch) + ''
}

dependencies {
    implementation 'com.christophecvb.touchportal:plugin-sdk:7.0.0-alpha-3'

    compile 'se.michaelthelin.spotify:spotify-web-api-java:6.3.0'
    compile 'org.imgscalr:imgscalr-lib:4.+'

    annotationProcessor 'com.christophecvb.touchportal:plugin-sdk-annotations-processor:7.0.0-alpha-3'

    testImplementation group: 'junit', name: 'junit', version: '4.12'
}
